### ISSUE TITLE
markbot

### ISSUE THREAD

**Issue by guer0125** [guer0125/stylish-beets#1]
markbot shows "The website isn't functioning as expected: The element, header nav:last-of-type a:not(.current), doesn't exist on the page"
I don't understand. does it want me to add it because it doesn't exist? where am i supposed to add it? it says it's referring to nav:hover but it's talking about HTML. 
in either case i do now have anything like that.

@thomasjbradley

**Comment by thomasjbradley** [comment]
It’s because there are no link `<a>` tags inside he navigation.
